/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sisrae;

import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Chess
 */
public class CRCancelarEvento extends javax.swing.JFrame {

    /**
     * Creates new form CRCancelarEvento
     */
    ArrayList<Integer> eliminar;
    int contador;
    JFrame jf;

    public CRCancelarEvento(int contador) {
        this.contador = contador;
    }

    public CRCancelarEvento(JFrame jf) {
        initComponents();
        this.jf = jf;
        Image imagen = new ImageIcon("img/IconoAdec.jpg").getImage();
        setIconImage(imagen);
    }

    public CRCancelarEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Selecciona = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        BotonEliminar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CANCELAR EVENTO");
        setPreferredSize(new java.awt.Dimension(565, 197));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Selecciona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeleccionaMouseClicked(evt);
            }
        });
        Selecciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionaActionPerformed(evt);
            }
        });

        jLabel1.setText("EVENTO");

        BotonEliminar.setText("Aceptar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        BotonCancelar.setText("Cancelar");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Selecciona, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonEliminar)
                        .addGap(41, 41, 41)
                        .addComponent(BotonCancelar)))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Selecciona, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEliminar)
                    .addComponent(BotonCancelar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        try {
            if (Selecciona.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "SELECCIONA EVENTO", "error", JOptionPane.ERROR_MESSAGE);
            } else {
                CRConsultasRegistroDeEventos x = new CRConsultasRegistroDeEventos();
                int id_evento = contador;
                x.EliminarEvento(id_evento);
                System.out.println("\"EVENTO ELIMINADO CON EXITO\"\tID = " + id_evento);
                jf.show();
                this.setVisible(false);
            }
        } catch (Exception ex) {
            Logger.getLogger(CRCancelarEvento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonEliminarActionPerformed
    private void SeleccionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionaActionPerformed
        CRConsultasRegistroDeEventos consulta = new CRConsultasRegistroDeEventos();
        try {
            eliminar = consulta.GetIndiceEnArray();
        } catch (SQLException ex) {
            Logger.getLogger(CRCancelarEvento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(CRCancelarEvento.class.getName()).log(Level.SEVERE, null, ex);
        }
//        for (int i = 0; i < this.eliminar.size(); i++) {
//            int variable = this.eliminar.get(i);
//            System.out.println("LISTA DE ENTEROS ACTIONPERFORMED POSICION " + i + " = " + variable);
//        }
        consulta.SetContador(eliminar.get(Selecciona.getSelectedIndex()));
        contador = consulta.getCont();
//        System.out.println("GETCONTADOR " + consulta.getCont());
        System.out.println("\nID DEL EVENTO A ELMINAR = " + eliminar.get(Selecciona.getSelectedIndex()));
//        System.out.println("INDEX BOTON = " + Selecciona.getSelectedIndex() + "  ITEM BOTON -> " + Selecciona.getSelectedItem());
        Selecciona.enable(true);
    }//GEN-LAST:event_SeleccionaActionPerformed

    private void SeleccionaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeleccionaMouseClicked
        try {
            CRConsultasRegistroDeEventos consulta = new CRConsultasRegistroDeEventos();
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            ArrayList<String> arr = consulta.GetSeleccionaEvento();
            for (String arr1 : arr) {
                modelo.addElement(arr1);
            }
            Selecciona.setModel(modelo);
        } catch (SQLException | InstantiationException ex) {
            Logger.getLogger(CRCrearEventos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SeleccionaMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        jf.show();
        this.jf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        jf.show();
        this.setVisible(false);
    }//GEN-LAST:event_BotonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRCancelarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRCancelarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRCancelarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRCancelarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRCancelarEvento().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JComboBox Selecciona;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
