/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * INGRESA.java
 *
 * Created on 25-abr-2014, 14:36:04
 */
package formularios;



import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Martínez Guerrero
 */
public class INGRESA extends javax.swing.JFrame {
String nom;


    /** Creates new form INGRESA */
    public INGRESA() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        InicioSesion = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nom_usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        contrasenia = new javax.swing.JPasswordField();

        jScrollPane1.setViewportView(jTextPane1);

        jTextField3.setText("jTextField3");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INGRESA");
        setBackground(new java.awt.Color(0, 102, 255));
        setMinimumSize(new java.awt.Dimension(2, 2));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(513, 307));

        InicioSesion.setBackground(new java.awt.Color(0, 0, 102));
        InicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        InicioSesion.setText("Iniciar Sesión");
        InicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioSesionActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Nombre del Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        nom_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_usuarioActionPerformed(evt);
            }
        });
        nom_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nom_usuarioKeyTyped(evt);
            }
        });

        jLabel3.setText("Nombre de usuario:");

        jLabel4.setText("Contraseña:");

        contrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraseniaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(713, 713, 713)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nom_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(contrasenia))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(InicioSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(InicioSesion)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
private String Desencriptacion(String contra)
{
    String pass = contra;
    
    char ayuda;

char ArrePass[] = new char [pass.length()];
    
    for (int j = 0 ; j < pass.length() ; j++)
                {
                    ArrePass[j]=pass.charAt(j);
                } 
    
    
    for (int i = 0 ; i < 7 ; i++)
        {
           ayuda =  ArrePass[0];
           for (int j = 0; j < ArrePass.length-1 ; j++)
                {
                    ArrePass[j]=ArrePass[j+1];          
                } 
           ArrePass[ArrePass.length-1]=ayuda; 
        } 
    
    pass="";
    
    for(int i = 0 ; i < ArrePass.length ; i++)
    {
        pass = pass + ArrePass[i];
    }
    
    return pass;
}
    
private void Actualizar(String usuario, String contrasenia, String intentos)
{
    String sql;
    String user = usuario;
    String contra = contrasenia;
    String inten = intentos;
    
    int intenum = Integer.parseInt(inten);
    
    intenum = intenum+1;
    
    if(intenum==3)
    {
        sql="update tabla set CONTRASENIA='BLOQUEADO', INTENTOS="+intenum+" where USUARIO='"+user+"'";
        JOptionPane.showMessageDialog(null, "Ya no le es permitido el acceso, usuario bloqueado");
    }
    else
        
    {       
        inten = intenum+"";
        sql="update tabla set INTENTOS="+inten+" where USUARIO='"+user+"'";
    }
    
    
    
    
    
    
    conectar cc=new conectar();

    Connection cn=  cc.conexion();
    
    //sql="INSERT INTO TABLA (USUARIO,CONTRASENIA,INTENTOS)VALUES(?,?,?)";
    
        try {
            com.mysql.jdbc.PreparedStatement pst = (com.mysql.jdbc.PreparedStatement) cn.prepareStatement(sql);
//            pst.setString(1,user);
//            pst.setString(2,contra);
//            pst.setString(3,inten);
            int n=pst.executeUpdate();
            
            
            
            if(n>0)
            {
                //JOptionPane.showMessageDialog(null,"Registro Guardado con Exito");
              
                
            }

            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ingreClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
    
private void InicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioSesionActionPerformed
 
       
        String pass;
        String sql;
        boolean bandera=true, otra=true;
        nom=nom_usuario.getText();
        pass=contrasenia.getText();
        
        if(nom.length()==10 && pass.length()>7)
        {
            sql = "SELECT * FROM tabla";
    
    
            conectar cc = new conectar();
            Connection cn = cc.conexion();

            try 
            { 
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);

                while ( rs.next() && bandera )
                {    
                    if(nom.equalsIgnoreCase(rs.getString("USUARIO")))
                            {
                                //JOptionPane.showMessageDialog(null, rs.getString("CONTRASENIA"));
                                if(rs.getString("CONTRASENIA").equals("BLOQUEADO"))
                                {
                                    nom_usuario.setText("");
                                    contrasenia.setText("");
                                JOptionPane.showMessageDialog(null, "No le es permitido el acceso, usuario bloqueado");
                                otra = false;
                                }

                                else
                                {
                                    //JOptionPane.showMessageDialog(null, rs.getString("CONTRASENIA"));
                                    String contraseniaDes = Desencriptacion(rs.getString("CONTRASENIA"));
                                    //JOptionPane.showMessageDialog(null, contraseniaDes+"----"+pass);
                                    
                                    if(contraseniaDes.equals(pass)) 
                                    {
                                        JOptionPane.showMessageDialog(null, "Sesión iniciada");
                                        bandera = false;
                                        otra = false;
                                        nom_usuario.setText("");
                                        contrasenia.setText("");
                                    }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
                                        Actualizar(rs.getString("USUARIO"), rs.getString("CONTRASENIA"),rs.getString("INTENTOS"));
                                        otra = false;
                                        
                                        contrasenia.setText("");
                                    }
                                }
                            }

                }
                
                if(otra == true)         
                {
                        JOptionPane.showMessageDialog(null, "Usuario no encontrado, intente de nuevo");
                        nom_usuario.setText("");
                        contrasenia.setText("");
                }
                    




            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(INGRESA.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(nom.length()==0)
            JOptionPane.showMessageDialog(null,"Por favor, escriba un nombre de usuario");
        else
        {
            if(nom.length()<10)
                JOptionPane.showMessageDialog(null, "El nombre de usuario debe contener mínimo 10 letras, evite usar caracteres especiales");
            else
                if(pass.length()<8)
                JOptionPane.showMessageDialog(null, "Contraseña inválida, use al menos 8 caracteres (letras y/o números)");
        }

    
    
    
    
    
    
    
    
            
    
       
       
}//GEN-LAST:event_InicioSesionActionPerformed

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void nom_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_usuarioActionPerformed

    
    
    
    private void nom_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_usuarioKeyTyped
        char car = evt.getKeyChar();
        if(nom_usuario.getText().length()==10)evt.consume();       
        if(  ( car < 'a' || car > 'z' ) && ( car < 'A'|| car > 'Z') )evt.consume();
        //if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_nom_usuarioKeyTyped

    private void contraseniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseniaKeyTyped
        char car = evt.getKeyChar();
        if(((car<'a' || car>'z') && (car<'A' || car>'Z')) && (car<'0' || car>'9')) evt.consume();     
                // TODO add your handling code here:
    }//GEN-LAST:event_contraseniaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INGRESA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INGRESA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INGRESA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INGRESA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new INGRESA().setVisible(true);
              
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InicioSesion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField contrasenia;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField nom_usuario;
    // End of variables declaration//GEN-END:variables
}
